;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-window
        backward-sexp
        complete-symbol
        crux-move-beginning-of-line
        forward-sexp
        helm-mini
        helm-show-kill-ring
        kill-region
        query-replace-regexp
        restclient-toggle-body-visibility-or-indent
        slime-autodoc-space
        sp-remove-active-pair-overlay
        ))

(setq mc/cmds-to-run-once
      '(
        helm-confirm-and-exit-minibuffer
        ))
