;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-window
        backward-sexp
        beginning-of-buffer
        complete-symbol
        crux-move-beginning-of-line
        dabbrev-expand
        electric-newline-and-maybe-indent
        forward-sexp
        helm-M-x
        helm-mini
        helm-show-kill-ring
        indent-for-tab-command
        kill-region
        paredit-backslash
        paredit-backward
        paredit-backward-kill-word
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-open-round
        paredit-wrap-round
        query-replace-regexp
        restclient-toggle-body-visibility-or-indent
        sh-assignment
        slime-autodoc-space
        slime-compile-and-load-file
        slime-compile-defun
        sp-remove-active-pair-overlay
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        helm-confirm-and-exit-minibuffer
        ))
